# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myte < Formula
  desc "myte CLI"
  homepage "https://github.com/tianweilong/myte-dist"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.0/myte_0.1.0_darwin_amd64.tar.gz"
      sha256 "30e4bd945fdd5e52c4de609f82c58210b9794400f0cd7af42b1f95d338896196"

      define_method(:install) do
        bin.install "myte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.0/myte_0.1.0_darwin_arm64.tar.gz"
      sha256 "b490a5378f2b6d943a5c9eccbefe97f39c9bddc243eb076820e544613264706a"

      define_method(:install) do
        bin.install "myte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.0/myte_0.1.0_linux_amd64.tar.gz"
      sha256 "88cd1c105e7d5877e2bd36d9ba35a2fb04f2097d71192d00fb4c193184ef7864"
      define_method(:install) do
        bin.install "myte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.0/myte_0.1.0_linux_arm64.tar.gz"
      sha256 "7fc4cc8c8d85404b813d65a52f67b1d0833328c33d49ccbd8eb18f499ac26d2e"
      define_method(:install) do
        bin.install "myte"
      end
    end
  end

  test do
    system "#{bin}/myte", "self", "version", "show"
  end
end
