# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myte < Formula
  desc "myte CLI"
  homepage "https://github.com/tianweilong/myte-dist"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.1/myte_0.1.1_darwin_amd64.tar.gz"
      sha256 "3159e5a898f8d0ff6b8442ea8f674949648795c3105a1ac5ee5fbb5f0fd060c5"

      define_method(:install) do
        bin.install "myte"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.1/myte_0.1.1_darwin_arm64.tar.gz"
      sha256 "ecdefc141944df9e62cc1e9e71ef5fe7b96b0583d718244f42039b55b1ecace0"

      define_method(:install) do
        bin.install "myte"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.1/myte_0.1.1_linux_amd64.tar.gz"
      sha256 "995251bb952a69e3aad46d0355e7d0fc6ae0de95180f4224d26ce47af95ee70f"
      define_method(:install) do
        bin.install "myte"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tianweilong/myte-dist/releases/download/v0.1.1/myte_0.1.1_linux_arm64.tar.gz"
      sha256 "1ee57c739fb275f5292620dd2926a392f3a7fb951be87a299ee28dfd3ec68bb1"
      define_method(:install) do
        bin.install "myte"
      end
    end
  end

  test do
    system "#{bin}/myte", "self", "version", "show"
  end
end
